version: '3.8'

services:
  preprocess:
    build:
      context: .
      dockerfile: preprocess/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_preprocess:latest
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  train_dcgan:
    build:
      context: .
      dockerfile: train_dcgan/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_train_dcgan:latest
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  train_wgangp:
    build:
      context: .
      dockerfile: train_wgangp/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_train_wgangp:latest
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  evaluate_fid_kid:
    build:
      context: .
      dockerfile: evaluate_fid_kid/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_evaluate_fid_kid:latest
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  evaluate_privacy:
    build:
      context: .
      dockerfile: evaluate_privacy/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_evaluate_privacy:latest
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  evaluate_progression_animation:
    build:
      context: .
      dockerfile: evaluate_progression_animation/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_evaluate_progression_animation:latest
    volumes:
      - ./runs:/app/runs

  generate:
    build:
      context: .
      dockerfile: generate/Dockerfile
    image: ghcr.io/sydgep/docker-images/brats_generate:latest
    volumes:
      - ./data:/app/data
      - ./runs:/app/runs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
